=== JavierRegalado/PaginaWeb_Macrosoft/XML/Animales.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="animales">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="animal" maxOccurs="unbounded">
                    <xs:complexType>
                        
                        <xs:sequence>
                            
                            <xs:element name="nombre" type="xs:string"></xs:element>
                            <xs:element name="edad" type="xs:int"></xs:element>
                            <xs:element name="raza" type="xs:string"></xs:element>
                            
                            <xs:element name="caracteristicas" type="xs:string" minOccurs="1"></xs:element>
                            <xs:element name="necesidadesEspeciales" type="xs:string" minOccurs="0"></xs:element>
                        
                        </xs:sequence>
                        
                        <xs:attribute name="idCentroAnimal" type="xs:boolean"></xs:attribute>
                        
                        <xs:attribute name="disponibilidad" type="xs:boolean"></xs:attribute>
                        
                        <xs:attribute name="idAnimal" type="xs:int" use="required"></xs:attribute>
                        
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== JavierRegalado/PaginaWeb_Macrosoft/XML/Animales.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet  type="text/xsl" href="Animales.xslt"?>
<animales xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Animales.xsd">
    <animal idCentroAnimal="1" disponibilidad="1" idAnimal="1">
        <nombre>Luna</nombre>
        <edad>5</edad>
        <raza>Labrador</raza>
        <caracteristicas>Muy juguetona</caracteristicas>
        <necesidadesEspeciales>ninguna</necesidadesEspeciales>
    </animal>
    <animal idCentroAnimal="1" disponibilidad="1" idAnimal="2">
        <nombre>Max</nombre>
        <edad>2</edad>
        <raza>Gato Siames</raza>
        <caracteristicas>Tranquilo</caracteristicas>
        <necesidadesEspeciales>ninguna</necesidadesEspeciales>
    </animal>
        <animal idCentroAnimal="1" disponibilidad="1" idAnimal="3">
        <nombre>Rocky</nombre>
        <edad>8</edad>
        <raza>Pastor Alemán</raza>
        <caracteristicas>Protector</caracteristicas>
        <necesidadesEspeciales>Dieta especial</necesidadesEspeciales>
    </animal>
        <animal idCentroAnimal="1" disponibilidad="1" idAnimal="4">
        <nombre>Mia</nombre>
        <edad>1</edad>
        <raza>Gato Persa</raza>
        <caracteristicas>Perezosa</caracteristicas>
        <necesidadesEspeciales>Cepillado</necesidadesEspeciales>
    </animal>
        <animal idCentroAnimal="1" disponibilidad="1" idAnimal="5">
        <nombre>Kira</nombre>
        <edad>4</edad>
        <raza>Bichón</raza>
        <caracteristicas>Sociable</caracteristicas>
        <necesidadesEspeciales>ninguna</necesidadesEspeciales>
    </animal>
</animales>
