=== JavierRegalado/PaginaWeb_Macrosoft/XML/Personas.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="empresa">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="persona" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string"></xs:element>
                            <xs:element name="usuario" type="xs:string"></xs:element>
                            
                            <xs:element name="contra">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="5"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>

                            <xs:element name="email">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>

                            <xs:element name="adoptante" type="xs:boolean"></xs:element>
                            <xs:element name="voluntario" type="xs:boolean"></xs:element>
                            <xs:element name="donante" type="xs:boolean"></xs:element>
                        </xs:sequence>
                        
                        <xs:attribute name="dni">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:pattern value="9"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>

                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="nombreEmpresa" type="xs:string" use="required"></xs:attribute>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== JavierRegalado/PaginaWeb_Macrosoft/XML/Personas.xml
<?xml version="1.0" encoding="UTF-8"?>
<empresa nombreEmpresa="Amigos Peludos" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Personas.xsd">
    <persona dni="65432109Q">
        <nombre>Quique Vela</nombre>
        <usuario>quiquev</usuario>
        <contra>LaMejorContraseña@</contra>
        <email>quique.vela@email.com</email>
        <adoptante>true</adoptante>
        <voluntario>true</voluntario>
        <donante>true</donante>
    </persona>
    <persona dni="67890123G">
        <nombre>Gema Torres</nombre>
        <usuario>gemat</usuario>
        <contra>TodoParaEllos$@</contra>
        <email>gema.torres@email.com</email>
        <adoptante>true</adoptante>
        <voluntario>true</voluntario>
        <donante>true</donante>
    </persona>
    <persona dni="76543210R">
        <nombre>Rosa Nieto</nombre>
        <usuario>gemat</usuario>
        <contra>PatitasFelices</contra>
        <email>rosa.nieto@email.com</email>
        <adoptante>true</adoptante>
        <voluntario>false</voluntario>
        <donante>false</donante>
    </persona>
    <persona dni="78901234H">
        <nombre>Héctor Martín</nombre>
        <usuario>hectorm</usuario>
        <contra>AdoptaHoy@</contra>
        <email>hector.martin@email.com</email>
        <adoptante>true</adoptante>
        <voluntario>false</voluntario>
        <donante>false</donante>
    </persona>
    <persona dni="87654321S">
        <nombre>Sonia Echevarria</nombre>
        <usuario>soniae</usuario>
        <contra>ComidaParaTodos#</contra>
        <email>sonia.echevarria@email.com</email>
        <adoptante>false</adoptante>
        <voluntario>true</voluntario>
        <donante>false</donante>
    </persona>
</empresa>
